-- Global default compliance rules (business_id NULL). Businesses can disable any of these via rule_overrides
-- and add their own rules with business_id set.

INSERT INTO compliance_rules (id, business_id, name, description, kind, pattern, applies_to, severity, action, category) VALUES
-- ===== Incoming review triage =====
('11111111-0000-4000-8000-000000000001', NULL, 'Legal threat in review', 'Reviewer mentions lawsuits, attorneys, or regulators. Route to a human before replying.', 'regex', '\b(lawsuit|sue\b|suing|attorney|lawyer|legal action|small claims|better business bureau|\bBBB\b|attorney general|health department|file a complaint)', 'review', 'warn', 'escalate', 'legal'),
('11111111-0000-4000-8000-000000000002', NULL, 'Health or safety allegation', 'Claims of injury, illness, unsafe conditions, harassment, or discrimination. Escalate for liability review.', 'regex', '\b(food poisoning|got sick|injur(y|ed)|unsafe|hazard|harass|assault|discriminat|racis|sexist|stole|theft|fire code|mold\b)', 'review', 'warn', 'escalate', 'safety'),
('11111111-0000-4000-8000-000000000003', NULL, 'Media or press mention', 'Reviewer identifies as press or threatens media exposure.', 'regex', '\b(journalist|reporter|news station|channel \d|local news|going viral|expose you)', 'review', 'info', 'escalate', 'pr'),
('11111111-0000-4000-8000-000000000004', NULL, 'Refund or chargeback demand', 'Explicit refund, chargeback, or dispute demand. Flag for owner follow-up.', 'regex', '\b(refund|charge ?back|dispute (the|this|my) charge|money back)', 'review', 'info', 'flag', 'billing'),
('11111111-0000-4000-8000-000000000005', NULL, 'Personal data exposed in review', 'Reviewer posted a phone number, email, or address (theirs or an employee''s).', 'regex', '(\b\d{3}[-. ]\d{3}[-. ]\d{4}\b|[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,})', 'review', 'warn', 'flag', 'privacy'),
('11111111-0000-4000-8000-000000000006', NULL, 'Incentivized review admission', 'Reviewer says they were paid, given a discount, or asked to review (FTC Endorsement Guides).', 'regex', '\b(paid me|gave me a (discount|gift card|free)|in exchange for (a|this|my) review|asked me to (leave|write) (a|this) review)', 'review', 'warn', 'flag', 'ftc'),
('11111111-0000-4000-8000-000000000007', NULL, 'Suspected fake or competitor review', 'AI judgment: review reads as fabricated, off-topic, spam, or planted by a competitor.', 'ai', 'Does this review appear fabricated, spam, off-topic, or planted by a competitor? Signs: no specific details, generic praise or attack, mentions a competitor by name favorably, contradicts itself.', 'review', 'info', 'flag', 'ftc'),
('11111111-0000-4000-8000-000000000008', NULL, 'Employee named and attacked', 'AI judgment: review names a specific employee and makes personal accusations about them.', 'ai', 'Does this review name a specific employee (first/last name or unique identifier) and make personal accusations or insults about them, beyond describing the service?', 'review', 'warn', 'escalate', 'hr'),
-- ===== Outgoing reply guardrails =====
('22222222-0000-4000-8000-000000000001', NULL, 'No incentives to change a review', 'FTC: never offer a discount, refund, gift, or freebie conditioned on editing or removing a review.', 'regex', '\b(discount|coupon|gift card|free|refund|credit)\b[^.]{0,80}\b(review|rating|stars?)\b', 'response', 'block', 'block', 'ftc'),
('22222222-0000-4000-8000-000000000002', NULL, 'No asking to remove or change the review', 'Platform TOS: do not ask the reviewer to delete, edit, or raise their rating.', 'regex', '\b(remove|delete|take down|edit|change|update|reconsider)\b[^.]{0,40}\b(your|the|this)\s+(review|rating|stars?)', 'response', 'block', 'block', 'platform_tos'),
('22222222-0000-4000-8000-000000000003', NULL, 'No personal data in reply', 'Never disclose phone numbers, emails, addresses, account or order numbers of the customer.', 'regex', '(\b\d{3}[-. ]\d{3}[-. ]\d{4}\b|[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}|\b(account|order|invoice|member) ?(number|#|no\.?)\s*:?\s*\w{4,})', 'response', 'block', 'block', 'privacy'),
('22222222-0000-4000-8000-000000000004', NULL, 'No legal threats in reply', 'Never threaten legal action or accuse the reviewer of defamation.', 'regex', '\b(defamation|defamatory|libel|slander|legal action|our (lawyer|attorney)|cease and desist|we will sue)', 'response', 'block', 'block', 'legal'),
('22222222-0000-4000-8000-000000000005', NULL, 'No hostility or profanity', 'Replies must stay professional. No insults, sarcasm, or profanity.', 'regex', '\b(idiot|stupid|liar|shut up|damn|hell\b|crap|screw you|f+u+c+k|sh[i1]t|b[i1]tch|a[s5]{2})', 'response', 'block', 'block', 'tone'),
('22222222-0000-4000-8000-000000000006', NULL, 'No admission of legal fault', 'Avoid statements that admit liability, negligence, or law-breaking (e.g., "we were negligent", "it was our fault you got sick").', 'regex', '\b(we (were|are) (negligent|liable|at fault)|our (negligence|liability)|we broke the law|we violated)', 'response', 'block', 'block', 'legal'),
('22222222-0000-4000-8000-000000000007', NULL, 'No blaming or contradicting the customer', 'AI judgment: reply argues with the reviewer, calls them wrong, or blames them for the experience.', 'ai', 'Does this reply blame the customer, call them dishonest or mistaken, argue point-by-point, or otherwise fail to take ownership? A calm clarification of policy is fine; a rebuttal is not.', 'response', 'warn', 'flag', 'tone'),
('22222222-0000-4000-8000-000000000008', NULL, 'No confirmation of private details', 'AI judgment: reply confirms private facts about the customer (visit dates, purchases, health, finances, employment) that they did not state themselves.', 'ai', 'Does this reply reveal or confirm private details about the reviewer (what they bought, when they visited, medical, financial, or personal information) that the reviewer did not already state in the review?', 'response', 'block', 'block', 'privacy'),
('22222222-0000-4000-8000-000000000009', NULL, 'No unverifiable claims or guarantees', 'AI judgment: reply promises outcomes, makes superlative or medical/legal claims that cannot be substantiated.', 'ai', 'Does this reply make unverifiable claims ("best in the city", "guaranteed results", "100% safe"), medical or legal advice, or promises the business may not be able to keep?', 'response', 'warn', 'flag', 'ftc'),
('22222222-0000-4000-8000-000000000010', NULL, 'Off-platform solicitation check', 'AI judgment: reply pushes the conversation off-platform in a way that looks like an attempt to bury the complaint rather than resolve it.', 'ai', 'Does this reply pressure the reviewer to take the conversation private as a way to avoid public accountability, rather than offering a genuine contact for resolution? A single polite invitation to contact the business with a real contact method is fine.', 'response', 'info', 'flag', 'platform_tos')
ON CONFLICT (id) DO NOTHING;